# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 22:50
from __future__ import unicode_literals

from django.db import migrations

def backwards(apps, schema_editor):
    """
    What to do when migrating backwards?
    In this case we do nothing
    """
    pass

def load_system_account(apps, schema_editor):
    """
    Load system account
    """
    system = {'pk': '4', 'email': 'general@solo.com.pt', 'balance': 50000,
                     'is_superuser': True, 'is_active': True, 'is_staff': True,
                     'is_system': True}

    model = apps.get_model("api", "Account")
    try:
        model.objects.get(pk=system['pk'])
    except model.DoesNotExist:
        model.objects.create(**system)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_system_account, backwards)
    ]
